-- ============================================================
-- Synch Cash - migracao do banco (Supabase / Postgres)
-- Rode este arquivo inteiro no SQL Editor do Supabase.
-- E seguro rodar mais de uma vez (tudo usa IF NOT EXISTS).
-- ============================================================


-- ------------------------------------------------------------
-- 1) despesas: colunas novas
--    A tabela ja existe com: id, nome_despesa, descricao, valor,
--    data, user_id, grupo_parcela, parcela_atual, parcela_total.
--    Aqui so entram os campos que o novo painel usa.
--
--    Mapeamento: nome_despesa = descricao da transacao,
--                descricao    = observacoes (campo livre).
-- ------------------------------------------------------------
alter table public.despesas add column if not exists categoria  text    not null default 'Outros';
alter table public.despesas add column if not exists tipo       text    not null default 'despesa';
alter table public.despesas add column if not exists conta      text;
alter table public.despesas add column if not exists status     text    not null default 'pago';
alter table public.despesas add column if not exists recorrente boolean not null default false;

-- So aceita os valores que a aplicacao conhece.
do $$ begin
  alter table public.despesas add constraint despesas_tipo_check   check (tipo   in ('despesa', 'receita'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.despesas add constraint despesas_status_check check (status in ('pago', 'pendente'));
exception when duplicate_object then null; end $$;

-- O painel filtra sempre por usuario + mes.
create index if not exists despesas_user_data_idx on public.despesas (user_id, data desc);


-- ------------------------------------------------------------
-- 2) contas (contas e cartoes)
-- ------------------------------------------------------------
create table if not exists public.contas (
  id      bigint generated by default as identity primary key,
  user_id uuid    not null references auth.users (id) on delete cascade,
  nome    text    not null,
  tipo    text    not null default 'Conta corrente',
  saldo   numeric not null default 0,
  detalhe text,
  cor     text    not null default '#22c55e',
  criado_em timestamptz not null default now()
);

create index if not exists contas_user_idx on public.contas (user_id);

-- Ciclo do cartao. 'saldo' fica sempre 0 nos cartoes: o valor da fatura
-- e calculado pelos lancamentos, nunca digitado.
alter table public.contas add column if not exists fechamento integer default 28;
alter table public.contas add column if not exists vencimento integer default 10;


-- ------------------------------------------------------------
-- 3) faturas: uma linha por cartao por mes, criada so quando a
--     fatura e paga. O valor nao fica aqui -- ele vem das despesas.
--     'valor_pago' guarda quanto saiu de fato, pra reabrir devolver
--     exatamente o que foi descontado.
-- ------------------------------------------------------------
create table if not exists public.faturas (
  id         bigint generated by default as identity primary key,
  user_id    uuid    not null references auth.users (id) on delete cascade,
  conta_id   bigint  not null references public.contas (id) on delete cascade,
  mes        text    not null,
  status     text    not null default 'pendente',
  pago_com   bigint  references public.contas (id) on delete set null,
  valor_pago numeric,
  pago_em    date,
  unique (user_id, conta_id, mes)
);

create index if not exists faturas_user_idx on public.faturas (user_id, mes);

-- O pagamento da fatura vira uma transacao visivel em Transacoes. Este
-- vinculo marca essa linha como quitacao (nao gasto novo) e permite
-- desfaze-la junto quando a fatura e reaberta.
alter table public.despesas add column if not exists fatura_id bigint
  references public.faturas (id) on delete cascade;

create index if not exists despesas_fatura_idx on public.despesas (fatura_id);


-- ------------------------------------------------------------
-- 4) orcamentos (limite mensal por categoria)
-- ------------------------------------------------------------
create table if not exists public.orcamentos (
  id        bigint generated by default as identity primary key,
  user_id   uuid    not null references auth.users (id) on delete cascade,
  categoria text    not null,
  limite    numeric not null default 0,
  unique (user_id, categoria)
);


-- ------------------------------------------------------------
-- 5) recorrentes (cobrancas que se repetem todo mes)
-- ------------------------------------------------------------
create table if not exists public.recorrentes (
  id        bigint generated by default as identity primary key,
  user_id   uuid    not null references auth.users (id) on delete cascade,
  nome      text    not null,
  categoria text    not null default 'Assinaturas',
  valor     numeric not null default 0,
  dia       integer not null default 1,
  ativo     boolean not null default true,
  criado_em timestamptz not null default now()
);

create index if not exists recorrentes_user_idx on public.recorrentes (user_id);

-- De onde a cobranca sai (conta, dinheiro ou cartao). Guarda o nome, igual
-- ao campo 'conta' de despesas, pra os dois falarem a mesma lingua.
alter table public.recorrentes add column if not exists conta text;

-- Recorrencia tambem pode ser entrada (salario, aluguel recebido), nao so
-- cobranca. Sem isso, uma receita recorrente apareceria como despesa.
alter table public.recorrentes add column if not exists tipo text not null default 'despesa';

do $$ begin
  alter table public.recorrentes add constraint recorrentes_tipo_check check (tipo in ('despesa', 'receita'));
exception when duplicate_object then null; end $$;

-- Liga a despesa a regra que a gerou. E o que impede a mesma recorrencia
-- de ser lancada duas vezes no mesmo mes.
alter table public.despesas add column if not exists recorrente_id bigint
  references public.recorrentes (id) on delete set null;

create index if not exists despesas_recorrente_idx on public.despesas (recorrente_id);


-- ------------------------------------------------------------
-- 6) metas (objetivos financeiros)
-- ------------------------------------------------------------
create table if not exists public.metas (
  id       bigint generated by default as identity primary key,
  user_id  uuid    not null references auth.users (id) on delete cascade,
  nome     text    not null,
  guardado numeric not null default 0,
  alvo     numeric not null default 0,
  prazo    text,
  cor      text    not null default '#22c55e',
  criado_em timestamptz not null default now()
);

create index if not exists metas_user_idx on public.metas (user_id);


-- ------------------------------------------------------------
-- 7) preferencias (perfil e ajustes; 1 linha por usuario)
-- ------------------------------------------------------------
create table if not exists public.preferencias (
  user_id        uuid    primary key references auth.users (id) on delete cascade,
  nome           text,
  notificacoes   boolean not null default true,
  tema_escuro    boolean not null default true,
  resumo_semanal boolean not null default true,
  onboarding     boolean not null default false
);


-- ============================================================
-- 8) RLS: cada usuario so enxerga as proprias linhas.
--    Sem isso, qualquer usuario logado le os dados de todos.
-- ============================================================
alter table public.despesas     enable row level security;
alter table public.contas       enable row level security;
alter table public.orcamentos   enable row level security;
alter table public.recorrentes  enable row level security;
alter table public.metas        enable row level security;
alter table public.faturas      enable row level security;
alter table public.preferencias enable row level security;

-- Uma policy "tudo" por tabela: le/insere/edita/apaga apenas o proprio dado.
do $$
declare
  t text;
begin
  foreach t in array array['despesas', 'contas', 'orcamentos', 'recorrentes', 'metas', 'preferencias', 'faturas']
  loop
    execute format('drop policy if exists %I on public.%I', t || '_proprio', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)',
      t || '_proprio', t
    );
  end loop;
end $$;


-- ============================================================
-- 9) Orcamentos padrao para quem ja tem conta criada.
--    Usuarios novos recebem esses limites pela aplicacao.
-- ============================================================
insert into public.orcamentos (user_id, categoria, limite)
select u.id, c.categoria, c.limite
from auth.users u
cross join (values
  ('Moradia',     1600),
  ('Alimentação', 1100),
  ('Transporte',   650),
  ('Lazer',        450),
  ('Assinaturas',  300),
  ('Outros',       900)
) as c (categoria, limite)
on conflict (user_id, categoria) do nothing;
