-- ============================================================
-- Synch Cash - migracao do banco (Supabase / Postgres)
-- Rode este arquivo inteiro no SQL Editor do Supabase.
-- E seguro rodar mais de uma vez (tudo usa IF NOT EXISTS).
-- ============================================================


-- ------------------------------------------------------------
-- 1) despesas: colunas novas
--    A tabela ja existe com: id, nome_despesa, descricao, valor,
--    data, user_id, grupo_parcela, parcela_atual, parcela_total.
--    Aqui so entram os campos que o novo painel usa.
--
--    Mapeamento: nome_despesa = descricao da transacao,
--                descricao    = observacoes (campo livre).
-- ------------------------------------------------------------
alter table public.despesas add column if not exists categoria  text    not null default 'Outros';
alter table public.despesas add column if not exists tipo       text    not null default 'despesa';
alter table public.despesas add column if not exists conta      text;
alter table public.despesas add column if not exists status     text    not null default 'pago';
alter table public.despesas add column if not exists recorrente boolean not null default false;

-- So aceita os valores que a aplicacao conhece.
do $$ begin
  alter table public.despesas add constraint despesas_tipo_check   check (tipo   in ('despesa', 'receita'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.despesas add constraint despesas_status_check check (status in ('pago', 'pendente'));
exception when duplicate_object then null; end $$;

-- O painel filtra sempre por usuario + mes.
create index if not exists despesas_user_data_idx on public.despesas (user_id, data desc);


-- ------------------------------------------------------------
-- 2) contas (contas e cartoes)
-- ------------------------------------------------------------
create table if not exists public.contas (
  id      bigint generated by default as identity primary key,
  user_id uuid    not null references auth.users (id) on delete cascade,
  nome    text    not null,
  tipo    text    not null default 'Conta corrente',
  saldo   numeric not null default 0,
  detalhe text,
  cor     text    not null default '#22c55e',
  criado_em timestamptz not null default now()
);

create index if not exists contas_user_idx on public.contas (user_id);

-- Ciclo do cartao. 'saldo' fica sempre 0 nos cartoes: o valor da fatura
-- e calculado pelos lancamentos, nunca digitado.
alter table public.contas add column if not exists fechamento integer default 28;
alter table public.contas add column if not exists vencimento integer default 10;


-- ------------------------------------------------------------
-- 3) faturas: uma linha por cartao por mes, criada so quando a
--     fatura e paga. O valor nao fica aqui -- ele vem das despesas.
--     'valor_pago' guarda quanto saiu de fato, pra reabrir devolver
--     exatamente o que foi descontado.
-- ------------------------------------------------------------
create table if not exists public.faturas (
  id         bigint generated by default as identity primary key,
  user_id    uuid    not null references auth.users (id) on delete cascade,
  conta_id   bigint  not null references public.contas (id) on delete cascade,
  mes        text    not null,
  status     text    not null default 'pendente',
  pago_com   bigint  references public.contas (id) on delete set null,
  valor_pago numeric,
  pago_em    date,
  unique (user_id, conta_id, mes)
);

create index if not exists faturas_user_idx on public.faturas (user_id, mes);

-- O pagamento da fatura vira uma transacao visivel em Transacoes. Este
-- vinculo marca essa linha como quitacao (nao gasto novo) e permite
-- desfaze-la junto quando a fatura e reaberta.
alter table public.despesas add column if not exists fatura_id bigint
  references public.faturas (id) on delete cascade;

create index if not exists despesas_fatura_idx on public.despesas (fatura_id);


-- ------------------------------------------------------------
-- 4) orcamentos (limite mensal por categoria)
-- ------------------------------------------------------------
create table if not exists public.orcamentos (
  id        bigint generated by default as identity primary key,
  user_id   uuid    not null references auth.users (id) on delete cascade,
  categoria text    not null,
  limite    numeric not null default 0,
  unique (user_id, categoria)
);


-- ------------------------------------------------------------
-- 5) recorrentes (cobrancas que se repetem todo mes)
-- ------------------------------------------------------------
create table if not exists public.recorrentes (
  id        bigint generated by default as identity primary key,
  user_id   uuid    not null references auth.users (id) on delete cascade,
  nome      text    not null,
  categoria text    not null default 'Assinaturas',
  valor     numeric not null default 0,
  dia       integer not null default 1,
  ativo     boolean not null default true,
  criado_em timestamptz not null default now()
);

create index if not exists recorrentes_user_idx on public.recorrentes (user_id);

-- De onde a cobranca sai (conta, dinheiro ou cartao). Guarda o nome, igual
-- ao campo 'conta' de despesas, pra os dois falarem a mesma lingua.
alter table public.recorrentes add column if not exists conta text;

-- Recorrencia tambem pode ser entrada (salario, aluguel recebido), nao so
-- cobranca. Sem isso, uma receita recorrente apareceria como despesa.
alter table public.recorrentes add column if not exists tipo text not null default 'despesa';

do $$ begin
  alter table public.recorrentes add constraint recorrentes_tipo_check check (tipo in ('despesa', 'receita'));
exception when duplicate_object then null; end $$;

-- Liga a despesa a regra que a gerou. E o que impede a mesma recorrencia
-- de ser lancada duas vezes no mesmo mes.
alter table public.despesas add column if not exists recorrente_id bigint
  references public.recorrentes (id) on delete set null;

create index if not exists despesas_recorrente_idx on public.despesas (recorrente_id);


-- ------------------------------------------------------------
-- 6) metas (objetivos financeiros)
-- ------------------------------------------------------------
create table if not exists public.metas (
  id       bigint generated by default as identity primary key,
  user_id  uuid    not null references auth.users (id) on delete cascade,
  nome     text    not null,
  guardado numeric not null default 0,
  alvo     numeric not null default 0,
  prazo    text,
  cor      text    not null default '#22c55e',
  criado_em timestamptz not null default now()
);

create index if not exists metas_user_idx on public.metas (user_id);


-- ------------------------------------------------------------
-- 7) preferencias (perfil e ajustes; 1 linha por usuario)
-- ------------------------------------------------------------
create table if not exists public.preferencias (
  user_id        uuid    primary key references auth.users (id) on delete cascade,
  nome           text,
  notificacoes   boolean not null default true,
  tema_escuro    boolean not null default true,
  resumo_semanal boolean not null default true,
  onboarding     boolean not null default false
);


-- ------------------------------------------------------------
-- 7b) assinaturas (plano do usuario: gratis / synch_ia).
--     So o webhook da Cakto escreve aqui, com a service_role key
--     (que ignora RLS) -- por isso essa tabela NAO entra na policy
--     generica "tudo" la embaixo. O usuario so pode ler a propria linha.
-- ------------------------------------------------------------
create table if not exists public.assinaturas (
  user_id       uuid    primary key references auth.users (id) on delete cascade,
  plano         text    not null default 'gratis',
  cakto_evento  text,
  cakto_id      text,
  atualizada_em timestamptz not null default now()
);

-- Se a tabela ja existia (de uma tentativa anterior) sem essas colunas,
-- o "create table if not exists" acima e um no-op e elas nunca entram --
-- por isso garante cada uma aqui tambem, idempotente.
alter table public.assinaturas add column if not exists plano         text not null default 'gratis';
alter table public.assinaturas add column if not exists cakto_evento  text;
alter table public.assinaturas add column if not exists cakto_id      text;
alter table public.assinaturas add column if not exists atualizada_em timestamptz not null default now();

do $$ begin
  alter table public.assinaturas add constraint assinaturas_plano_check
    check (plano in ('gratis', 'synch_ia'));
exception when duplicate_object then null; end $$;

-- Correcao de uma migracao anterior: antes desta tabela ter a coluna 'plano',
-- o controle de acesso era so um booleano 'ativa' (versao antiga do webhook).
-- Quando 'plano' foi criada, o "add column ... default 'gratis'" acima
-- sobrescreveu SEM QUERER quem ja era assinante ativo antes dessa migracao --
-- a pessoa continuava marcada como paga na Cakto (cakto_evento de compra/
-- renovacao), mas o plano dela virou 'gratis' e nunca mais foi corrigido
-- (a Cakto nao reenvia o evento de compra original). Aqui reaplica o plano
-- certo pra quem ficou nesse estado; e idempotente -- depois de corrigida
-- uma vez, a linha nao bate mais nessa condicao e roda de novo sem efeito.
update public.assinaturas
   set plano = 'synch_ia', atualizada_em = now()
 where plano = 'gratis'
   and cakto_evento in ('purchase_approved', 'subscription_created', 'subscription_renewed', 'subscription_resumed');

-- Quem paga na Cakto ANTES de criar conta no app: o webhook nao acha ninguem
-- pra marcar em "assinaturas" (nao existe user_id ainda) e, sem isso, o
-- pagamento seria esquecido pra sempre. Guarda o estado por e-mail aqui; ao
-- criar a conta ou entrar com esse e-mail, o backend aplica e limpa a linha.
-- RLS fica ligado e SEM NENHUMA policy: só a service_role (webhook e o
-- proprio backend, via conectar_admin) le e escreve; nenhum usuario logado
-- pode ver o e-mail ou o plano de outra pessoa aqui.
create table if not exists public.cakto_pendencias (
  email         text    primary key,
  plano         text    not null default 'gratis',
  cakto_evento  text,
  cakto_id      text,
  atualizada_em timestamptz not null default now()
);

do $$ begin
  alter table public.cakto_pendencias add constraint cakto_pendencias_plano_check
    check (plano in ('gratis', 'synch_ia'));
exception when duplicate_object then null; end $$;

alter table public.cakto_pendencias enable row level security;


-- ------------------------------------------------------------
-- 10) API nova (front Next.js): pagamento/estorno de fatura com
--     historico completo, ajuste manual, transferencias e os campos
--     que o novo painel espera em cada transacao.
--
--     Antes, "pagar fatura" so sabia PAGO/PENDENTE (1 pagamento
--     implicito). O front novo faz pagamento parcial + total, com
--     varios registros por fatura, estorno auditavel (nunca apaga o
--     original) e ajuste manual de conciliacao -- por isso essas duas
--     tabelas novas em vez de esticar 'faturas'.
-- ------------------------------------------------------------
create table if not exists public.fatura_pagamentos (
  id                  bigint generated by default as identity primary key,
  user_id             uuid    not null references auth.users (id) on delete cascade,
  conta_id            bigint  not null references public.contas (id) on delete cascade,
  ciclo               text    not null,
  conta_origem_id     bigint  not null references public.contas (id) on delete restrict,
  valor               numeric not null,
  data                date    not null,
  modo                text    not null default 'partial',
  status              text    not null default 'active',
  transacao_id        bigint  references public.despesas (id) on delete set null,
  transacao_estorno_id bigint references public.despesas (id) on delete set null,
  idempotency_key     text    not null,
  criado_em           timestamptz not null default now(),
  revertido_em        timestamptz,
  unique (user_id, idempotency_key)
);

do $$ begin
  alter table public.fatura_pagamentos add constraint fatura_pagamentos_modo_check check (modo in ('full', 'partial'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.fatura_pagamentos add constraint fatura_pagamentos_status_check check (status in ('active', 'reversed'));
exception when duplicate_object then null; end $$;

create index if not exists fatura_pagamentos_user_ciclo_idx on public.fatura_pagamentos (user_id, conta_id, ciclo);

create table if not exists public.fatura_ajustes (
  id            bigint generated by default as identity primary key,
  user_id       uuid    not null references auth.users (id) on delete cascade,
  conta_id      bigint  not null references public.contas (id) on delete cascade,
  ciclo         text    not null,
  valor         numeric not null,
  motivo        text    not null,
  status        text    not null default 'active',
  criado_em     timestamptz not null default now(),
  revertido_em  timestamptz
);

do $$ begin
  alter table public.fatura_ajustes add constraint fatura_ajustes_status_check check (status in ('active', 'reversed'));
exception when duplicate_object then null; end $$;

create index if not exists fatura_ajustes_user_ciclo_idx on public.fatura_ajustes (user_id, conta_id, ciclo);

-- Liga a transacao-espelho (o debito na conta de origem) ao registro de
-- pagamento -- e o que deixa reverter sem apagar o historico, diferente
-- do antigo fatura_id (que so sabia apagar).
alter table public.despesas add column if not exists fatura_pagamento_id bigint
  references public.fatura_pagamentos (id) on delete cascade;

create index if not exists despesas_fatura_pagamento_idx on public.despesas (fatura_pagamento_id);

-- Campos que o painel novo usa por transacao: natureza do lancamento
-- (compra/estorno/transferencia), par de uma transferencia, estabelecimento
-- normalizado, forma de pagamento, nome do comprovante e "revisado" na
-- central de qualidade. Tudo opcional -- nao quebra nenhuma linha existente.
alter table public.despesas add column if not exists kind text not null default 'purchase';
alter table public.despesas add column if not exists transfer_pair_id bigint references public.despesas (id) on delete set null;
alter table public.despesas add column if not exists merchant text;
alter table public.despesas add column if not exists payment_method text;
alter table public.despesas add column if not exists receipt_name text;
alter table public.despesas add column if not exists quality_resolved boolean not null default false;

do $$ begin
  alter table public.despesas add constraint despesas_kind_check check (kind in ('purchase', 'refund', 'transfer'));
exception when duplicate_object then null; end $$;

-- Limite de credito e os ultimos 4 digitos, so pra cartao -- o painel novo
-- mostra "limite usado" e o cartao com a bandeira/numero mascarado.
alter table public.contas add column if not exists limite_credito numeric;
alter table public.contas add column if not exists ultimos_digitos text;


-- ------------------------------------------------------------
-- 11) categorias (lista de categorias de cada usuario)
--     Antes as categorias eram uma lista fixa no codigo. Agora cada
--     usuario tem a sua: na primeira vez o app grava as padrao mais as
--     que ja existiam (orcamentos, transacoes), e dali em diante ele
--     cria e exclui as dele. "Outros" e "Receita" ficam sempre (o app
--     depende delas) e nunca podem ser excluidas.
-- ------------------------------------------------------------
create table if not exists public.categorias (
  id        bigint generated by default as identity primary key,
  user_id   uuid    not null references auth.users (id) on delete cascade,
  nome      text    not null,
  criado_em timestamptz not null default now(),
  unique (user_id, nome)
);

create index if not exists categorias_user_idx on public.categorias (user_id);


-- ============================================================
-- 8) RLS: cada usuario so enxerga as proprias linhas.
--    Sem isso, qualquer usuario logado le os dados de todos.
-- ============================================================
alter table public.despesas          enable row level security;
alter table public.contas            enable row level security;
alter table public.orcamentos        enable row level security;
alter table public.recorrentes       enable row level security;
alter table public.metas             enable row level security;
alter table public.faturas           enable row level security;
alter table public.preferencias      enable row level security;
alter table public.assinaturas       enable row level security;
alter table public.fatura_pagamentos enable row level security;
alter table public.fatura_ajustes    enable row level security;
alter table public.categorias        enable row level security;

-- Uma policy "tudo" por tabela: le/insere/edita/apaga apenas o proprio dado.
do $$
declare
  t text;
begin
  foreach t in array array['despesas', 'contas', 'orcamentos', 'recorrentes', 'metas', 'preferencias', 'faturas', 'fatura_pagamentos', 'fatura_ajustes', 'categorias']
  loop
    execute format('drop policy if exists %I on public.%I', t || '_proprio', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)',
      t || '_proprio', t
    );
  end loop;
end $$;

-- assinaturas e diferente: o usuario so LE a propria linha. Escrever quem
-- e assinante e o webhook da Cakto (service_role), nunca o proprio usuario
-- -- senao qualquer um se marcaria como assinante sem pagar nada.
drop policy if exists assinaturas_leitura on public.assinaturas;
create policy assinaturas_leitura on public.assinaturas
  for select to authenticated using (auth.uid() = user_id);


-- ============================================================
-- 9) Orcamentos padrao para quem ja tem conta criada.
--    Usuarios novos recebem esses limites pela aplicacao.
-- ============================================================
insert into public.orcamentos (user_id, categoria, limite)
select u.id, c.categoria, c.limite
from auth.users u
cross join (values
  ('Moradia',     1600),
  ('Alimentação', 1100),
  ('Transporte',   650),
  ('Lazer',        450),
  ('Assinaturas',  300),
  ('Outros',       900)
) as c (categoria, limite)
on conflict (user_id, categoria) do nothing;
